version: '3.1'

services:
  adventure-cms:
    image: adventure-cms:latest
    restart: unless-stopped
    volumes:
      - ../app:/adventure
    ports:
      - '24678:24678'
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.22
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - adventure-cms-data:/data/db
    command: ["--logpath", "/var/log/mongodb/mongod.log"]

    # Only add port for debug purposes so that you can connect to MongoDB on localhost:8027
    ports:
      - '8027:${DB_PORT}'

volumes:
  adventure-cms-data:
