services:
  adventure-cms:
    image: adventure-cms:latest
    container_name: adventure-cms
    restart: unless-stopped
    volumes:
      - ../app:/adventure
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    command: bash -c "
        npm install --global serve &&
        npm run build &&
        serve -n -S dist/client"
    networks:
      - adventure-net

  mongodb:
    image: mongo:5
    container_name: adventure-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - adventure-cms-data:/data/db
    command: ["--logpath", "/var/log/mongodb/mongod.log"]
    networks:
      - adventure-net

volumes:
  adventure-cms-data:
    external: true
    name: adventure-cms_adventure-cms-data

networks:
  adventure-net:
    external: true
